GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzb25uZXJAZ21haWwuY29tIiwiaWF0IjoxNTEzMDM2Mzc2LCJleHAiOjE1MTM2NDExNzYsInN1YiI6IjVhMjllNDRlNGMwOTllMWExNTVhMjQ5NiJ9.ml9-1u14GHSn7e54_O0kcsEDNK4yNjDotATCPPGSY0g

### Register
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "nicksonner@gmail.com",
  "firstName": "Nick",
  "lastName": "Sonner",
  "password": "password"
}

### Sign in
POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "nicksonner@gmail.com",
  "password": "password"
}

### Create product
POST http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzb25uZXJAZ21haWwuY29tIiwiaWF0IjoxNTEzMDM2Mzc2LCJleHAiOjE1MTM2NDExNzYsInN1YiI6IjVhMjllNDRlNGMwOTllMWExNTVhMjQ5NiJ9.ml9-1u14GHSn7e54_O0kcsEDNK4yNjDotATCPPGSY0g
Content-Type: application/json

{
  "brandName": "Ford",
  "name": "Focus"
}

### Update product
PUT http://localhost:7000/products/5a28c95edff50e5b800e28ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzb25uZXJAZ21haWwuY29tIiwiaWF0IjoxNTEzMDM2Mzc2LCJleHAiOjE1MTM2NDExNzYsInN1YiI6IjVhMjllNDRlNGMwOTllMWExNTVhMjQ5NiJ9.ml9-1u14GHSn7e54_O0kcsEDNK4yNjDotATCPPGSY0g
Content-Type: application/json

{
  "brandName": "Holden",
  "name": "Commodore"
}

### Read wishlist
GET http://localhost:7000/wishlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzb25uZXJAZ21haWwuY29tIiwiaWF0IjoxNTEzMDM2Mzc2LCJleHAiOjE1MTM2NDExNzYsInN1YiI6IjVhMjllNDRlNGMwOTllMWExNTVhMjQ5NiJ9.ml9-1u14GHSn7e54_O0kcsEDNK4yNjDotATCPPGSY0g

### Add to wishlist
POST http://localhost:7000/wishlist/products/5a2742308714fc738c09968b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzb25uZXJAZ21haWwuY29tIiwiaWF0IjoxNTEzMDM2Mzc2LCJleHAiOjE1MTM2NDExNzYsInN1YiI6IjVhMjllNDRlNGMwOTllMWExNTVhMjQ5NiJ9.ml9-1u14GHSn7e54_O0kcsEDNK4yNjDotATCPPGSY0g

### Remove from wishlist
DELETE http://localhost:7000/wishlist/products/5a2742308714fc738c09968b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pY2tzb25uZXJAZ21haWwuY29tIiwiaWF0IjoxNTEzMDM2Mzc2LCJleHAiOjE1MTM2NDExNzYsInN1YiI6IjVhMjllNDRlNGMwOTllMWExNTVhMjQ5NiJ9.ml9-1u14GHSn7e54_O0kcsEDNK4yNjDotATCPPGSY0g